version: 2.1

commands:
  setup_ruby:
    steps:
      - run:
          name: Install bundler gem
          command: gem install bundler --version '~> 2.2'
      - run:
          name: Install Ruby dependencies
          command: bundle check || bundle install

executors:
  ruby:
    parameters:
      image:
        default: "cimg/ruby:3.0"
        type: string
    docker:
      - image: << parameters.image >>
    resource_class: small

orbs:
  ruby: circleci/ruby@1.2
 
jobs:
  test:
    parameters:
      ruby-image:
        type: string
    executor:
      name: ruby
      image: << parameters.ruby-image >>
    steps:
      - checkout
      - setup_ruby
      - ruby/rubocop-check
      - ruby/rspec-test
  docs:
    executor:
      name: ruby
    steps:
      - checkout
      - setup_ruby
      - run:
          name: Build documentation with Yard
          command: bundle exec yard
      - store_artifacts:
          path: doc
  test-regressions:
    executor:
      name: ruby
    steps:
      - checkout
      - setup_ruby
      - run:
          name: Install dependencies per Appraisal
          command: bundle exec appraisal install
      - run:
          name: Run tests per Appraisal
          command: bundle exec appraisal rspec
  coverage:
    executor:
      name: ruby
    environment:
      COVERAGE: true
    steps:
      - checkout
      - setup_ruby
      - run:
          name: Run tests with Simplecov enabled
          command: bundle exec rspec spec
      - store_artifacts:
          path: coverage
  code_examples:
    executor:
      name: ruby
    steps:
      - checkout
      - setup_ruby
      - run:
          name: Run "search and book" example
          command: bundle exec ruby examples/search_and_book.rb
      - run:
          name: Run "hold and pay later" example
          command: bundle exec ruby examples/hold_and_pay_later.rb
      - run:
          name: Run "exploring data" example
          command: bundle exec ruby examples/exploring_data.rb
      - run:
          name: Run "book with extra baggage" example
          command: bundle exec ruby examples/book_with_extra_baggage.rb
      - run:
          name: Run "book with seat" example
          command: bundle exec ruby examples/book_with_seat.rb
      - run:
          name: Run "book and change" example
          command: bundle exec ruby examples/book_and_change.rb
workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          matrix:
            parameters:
              ruby-image: ["cimg/ruby:2.6", "cimg/ruby:2.7", "cimg/ruby:3.0", "cimg/ruby:3.1"]
      - coverage
      - code_examples:
          requires:
            - test
      - docs
      - test-regressions
